In [ ]:
import pandas as pd

####Load Dataset

In [ ]:
data=pd.read_csv("Employee_Salary_Dataset.csv")

In [ ]:
data.head(10)

   ID  Experience_Years  Age  Gender   Salary
0   1                 5   28  Female   250000
1   2                 1   21    Male    50000
2   3                 3   23  Female   170000
3   4                 2   22    Male    25000
4   5                 1   17    Male    10000
5   6                25   62    Male  5001000
6   7                19   54  Female   800000
7   8                 2   21  Female     9000
8   9                10   36  Female    61500
9  10                15   54  Female   650000

###Explore Data

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                35 non-null     int64
 1   Experience_Years  35 non-null     int64
 2   Age               35 non-null     int64
 3   Gender            35 non-null     object
 4   Salary            35 non-null     int64
dtypes: int64(4), object(1)
memory usage: 1.5+ KB

In [ ]:
data.describe()

              ID  Experience_Years        Age        Salary
count  35.000000          35.00000  35.000000  3.500000e+01
mean   18.000000           9.20000  35.485714  2.059147e+06
std    10.246951           7.55295  14.643552  3.170124e+06
min     1.000000           1.00000  17.000000  3.000000e+03
25%     9.500000           2.50000  22.500000  2.250000e+04
50%    18.000000           6.00000  29.000000  2.500000e+05
75%    26.500000          15.00000  53.500000  3.270000e+06
max    35.000000          27.00000  62.000000  1.000000e+07

In [ ]:
data.isnull().sum()

ID                  0
Experience_Years    0
Age                 0
Gender              0
Salary              0
dtype: int64

###Handle Missing Data

In [ ]:
data['Age']=data['Age'].fillna(data['Age'].mean())
data['Salary']=data['Salary'].fillna(data['Salary'].mean())

In [ ]:
data.isnull().sum()

ID                  0
Experience_Years    0
Age                 0
Gender              0
Salary              0
dtype: int64

###Handle categorical Variables

lable Encoding on Nominal data

In [ ]:
from sklearn.preprocessing import LabelEncoder

le_Gender=LabelEncoder()
data['Gender_encoded']=le_Gender.fit_transform(data['Gender'])

data.head(6)

   ID  Experience_Years  Age  Gender   Salary  Gender_encoded
0   1                 5   28  Female   250000               0
1   2                 1   21    Male    50000               1
2   3                 3   23  Female   170000               0
3   4                 2   22    Male    25000               1
4   5                 1   17    Male    10000               1
5   6                25   62    Male  5001000               1

### Normalization

Data Scaling

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
data['Age_scaled']=scaler.fit_transform(data[['Age']])
data['Salary_scaled']=scaler.fit_transform(data[['Salary']])

data.head(6)

,ID,Experience_Years,Age,Gender,Salary,Gender_encoded,Age_scaled,Salary_scaled
0,1,5,28,Female,250000,0,0.244444,0.024707
1,2,1,21,Male,50000,1,0.088889,0.004701
2,3,3,23,Female,170000,0,0.133333,0.016705
3,4,2,22,Male,25000,1,0.111111,0.002201
4,5,1,17,Male,10000,1,0.000000,0.000700
5,6,25,62,Male,5001000,1,1.000000,0.499950